# -*- coding: utf-8 -*-
"""Guilherme Teruya - Projeto Módulo 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BWi2Y0jf9S2z89QqtRkGPpNFBarjqF6X

# Projeto Módulo 1
"""

# Calculadora de IMC
nome = input('Insira seu nome: ')
idade = input('Insira sua idade: ')
altura = float(input('Insira sua altura (ex.: X.XX): '))
peso = float(input('Insira seu peso (ex.: X.XX): ' ))

IMC = peso / (altura * altura)
print('Seu IMC é: ', IMC)

if IMC < 18.4:
    print('Atenção! Você pode estar abaixo do peso. Procure seu médico.')
elif IMC >= 18.5 and IMC <= 24.9:
    print('Parabéns! Você parece estar no peso ideal!')
elif IMC >= 25 and IMC <= 29.9:
    print('Cuidado! Você pode estar acima do peso. Procure seu médico.')
elif IMC >= 30 and IMC <= 39.9:
    print('Atenção! Você pode sofrer de obesidade. Procure seu médico.')
else:
    print('Alerta! Você pode sofrer de obesidade mórbida. Procure seu médico.')

# Calculando a diferença
if IMC > 24.9:
  x = IMC - 24.9
  print('Idealmente, você deve perder cerca de', x, 'kg.')
elif IMC < 18.5:
  y = 18.5 - IMC
  print('Idealmente, você deve ganhar cerca de', y, 'kg.')
else:
  pass
